Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.hostname = "Rancher-Server"
  config.vm.network "public_network"
  config.vm.provision "shell", path: "provision.sh"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
   end

end
